busapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # home urls
    path("", views.index, name="index"),
    path('bus-search', views.bus_search, name="bus_search"),
    # booking urls
    path('book/customer-info/', views.customer_info, name='customer_info'),
    path('booking-confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('booking/pay', views.pay, name="confirm_payment"),
    path('mpesa/callback/', views.callback, name="mpesa-callback"),
    path('bookings', views.all_bookings, name="bookings"),
    path('user-bookings', views.user_bookings, name="user_bookings"),
    # routes urls
    path('routes', views.routes, name="routes"),
    path('routes/delete/<int:pk>/', views.delete_route, name="delete_route"),
    path('route/edit/<int:route_id>/', views.edit_route, name='edit_route'),
    # buses urls
    path('buses/', views.list_buses, name='list_buses'),
    path('bus/edit/<int:bus_id>/', views.edit_bus, name='edit_bus'),
    path('buses/delete/<int:pk>/', views.delete_bus, name="delete_bus"),

]

busbooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .settings import DEBUG



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('busapp.urls')),
    path('', include('user.urls')),
]


if DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from .views import (
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

urlpatterns = [
    # auth urls
    path('signup/', views.register_user, name='register_user'),
    path('login/', views.login_view, name='login'),
    path('user-account/', views.user_account, name="user_account"),
    path('admin-account/', views.admin_account, name="admin_account"),
    path('admin-profile/', views.admin_profile, name="admin_profile" ),
    path('logout/', views.custom_logout, name='logout'),
    path('user-change-password/', views.user_change_password, name="user-change-password"),
    path('admin-change-password/', views.admin_change_password, name="admin-change-password"),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

busapp/models.py
from django.db import models
from django.utils import timezone


class Route(models.Model):
    starting_point = models.CharField(max_length=50)
    destination = models.CharField(max_length=50)
    price = models.BigIntegerField(default=0)
    
    def __str__(self):
        return self.starting_point + " - " + self.destination


class Bus(models.Model):
    number_plate = models.CharField(max_length=50)
    available_seats = models.IntegerField()
    status = models.CharField(max_length=30, default="AVAILABLE")
    route = models.ForeignKey(Route, on_delete=models.CASCADE, related_name='buses', default=1)
    travel_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.number_plate
    
    def remaining_seats(self):
        return self.available_seats  # Return the number of available seats
    
    
    
class Booking(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
    ]
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, default=True)
    customer_name = models.CharField(max_length=100, default="user")
    customer_email = models.EmailField(null=True)
    customer_phone = models.CharField(max_length=10, default=0)
    customer_id_number = models.CharField(max_length=20, default=1)
    booking_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')
    checkout_request_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.customer_name} - {self.bus} - Travel date {self.bus.travel_date}"



class Payment(models.Model):
    merchant_request_id = models.CharField(max_length=100, unique=True, null=True)
    checkout_request_id = models.CharField(max_length=100, unique=True, null=True)
    result_code = models.IntegerField(null=True, default=0)
    result_description = models.CharField(max_length=255, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    mpesa_receipt_number = models.CharField(max_length=100, null=True)
    balance = models.CharField(max_length=100, null=True, blank=True)  # Balance might not always be provided
    transaction_date = models.DateTimeField(null=True)  # Defaulting to null for better handling of empty dates
    phone_number = models.CharField(max_length=15, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.mpesa_receipt_number} - {self.amount} - {self.transaction_date}'

    def save(self, *args, **kwargs):
        # Ensure transaction_date is not set to a default invalid value
        if isinstance(self.transaction_date, int) and self.transaction_date == 0:
            self.transaction_date = None
        super(Payment, self).save(*args, **kwargs)

busapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db import transaction
from .models import Bus, Booking, Route, Payment
from .forms import CustomerInfoForm, BusSearchForm, RoutesForm, BusForm
from django.urls import reverse
from urllib.parse import urlencode
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django_daraja.mpesa.core import MpesaClient
from django.views.decorators.csrf import csrf_exempt
import datetime
import json

from django.db import IntegrityError



def bus_search(request):
    route_id = request.GET.get('route')
    travel_date = request.GET.get('travel_date')

    # Get the Route object using the route_id
    route = get_object_or_404(Route, id=route_id)
    request.session['route_id'] = route_id

    # Filter buses by route and travel date
    buses = Bus.objects.filter(route=route, travel_date=travel_date, status="AVAILABLE")

    if request.method == "POST":
        request.session['bus_id'] = request.POST.get('bus_id')
        bus_id = request.session.get('bus_id')
        bus = get_object_or_404(Bus, id=bus_id)
        if bus.status == "AVAILABLE":
            return redirect('customer_info')
        else:
            messages.error(request, 'Sorry, this bus is now full. Please choose another.')
    else:
        return render(request, "busapp/bus_search_results.html", {
            'buses': buses,
            'route': route,  # Pass the entire route object
            'travel_date': travel_date
        })



def index(request):
    form = BusSearchForm()

    if request.method == 'POST':
        form = BusSearchForm(request.POST)
        if form.is_valid():
            route = form.cleaned_data['route'].id  # Assuming route is a ForeignKey
            travel_date = form.cleaned_data['travel_date'].strftime('%Y-%m-%d')  # Format the date

            # Use urlencode to generate the query string
            query_string = urlencode({'route': route, 'travel_date': travel_date})
            url = f"{reverse('bus_search')}?{query_string}"
            return redirect(url)

    return render(request, 'busapp/index.html', {'form': form})


def customer_info(request):
    user = request.user

    if user.is_authenticated:
        # Get data from the user's profile
        profile = user.userprofile
        customer_data = {
            'full_name': user.get_full_name(),
            'email': user.email,
            'phone_number': profile.phone_no,
            'id_number': profile.id_number  
        }
        return create_booking(request, customer_data)
    
    # If the user is not authenticated or their profile lacks necessary info, show the form
    if request.method == 'POST':
        form = CustomerInfoForm(request.POST)
        if form.is_valid():
            return create_booking(request, form.cleaned_data)
    else:
        form = CustomerInfoForm()

    return render(request, 'busapp/booking/customer_info.html', {'form': form})

@transaction.atomic
def create_booking(request, customer_data):
    bus_id = request.session.get('bus_id')
    if not bus_id:
        messages.error(request, 'Bus selection is missing. Please select a bus first.')
        return redirect('index')

    route_id = request.session.get('route_id')
    route = get_object_or_404(Route, id=route_id)

    bus = get_object_or_404(Bus, id=bus_id)

    if bus.available_seats <= 0:
        messages.error(request, 'Sorry, the bus is fully booked.')
        return redirect('route_selection')

    try:
        booking = Booking.objects.create(
            bus=bus,
            route=route,
            customer_name=customer_data.get('full_name'),
            customer_email=customer_data.get('email'),
            customer_phone=customer_data.get('phone_number'),
            customer_id_number=customer_data.get('id_number'),
            status='Pending'  # Set initial status as 'Pending'
        )

        # Store booking_id and other necessary information in the session
        request.session['booking_id'] = booking.id
        request.session['price'] = bus.route.price
        request.session['phone_no'] = customer_data.get('phone_number')

        return redirect('booking_confirmation', booking_id=booking.id)

    except IntegrityError as e:
        messages.error(request, 'Please complete your profile with all required information.')
        return redirect('user_account')

def booking_confirmation(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    return render(request, 'busapp/booking/booking_confirmation.html', {'booking': booking})




@csrf_exempt
def pay(request):
    if request.method == 'POST':
        phone_no = request.session.get('phone_no')
        amount = request.session.get('price')

        # Retrieve the booking using the session's stored booking_id
        booking_id = request.session.get('booking_id')
        if not booking_id:
            messages.error(request, "Booking ID is missing. Please start the booking process again.")
            return redirect('index')

        booking = get_object_or_404(Booking, id=booking_id)

        cl = MpesaClient()

        phone_number = phone_no
        account_reference = 'reference'
        transaction_desc = 'Description'
        callback_url = 'https://api.darajambili.com/express-payment'

        try:
            response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
            data = response.json()

            # Accessing response attributes correctly
            if data['ResponseCode'] == '0':
                # Store checkout_request_id in the booking
                checkout_request_id = data['CheckoutRequestID']
                booking.checkout_request_id = checkout_request_id
                booking.save()

                messages.success(request, "An STK Push was sent to your phone, confirm to complete the payment. Thank you :)")
            else:
                messages.error(request, f"Payment failed: {data['ResponseDescription']}")
                booking.status = 'Cancelled'
                booking.save()
        except Exception as e:
            messages.error(request, f"An error occurred: {str(e)}")
            booking.status = 'Cancelled'
            booking.save()

        # Update bus availability
        bus = booking.bus
        bus.available_seats -= 1
        if bus.available_seats == 0:
            bus.status = 'BOOKED'
        bus.save()

        return redirect('index')
    else:
        amount = request.session.get('price')
        return render(request, 'busapp/booking/payment.html', {'price': amount})


@csrf_exempt
def callback(request):
    if request.method == 'POST':
        
        # Load the JSON data from the request
        result_json = json.loads(request.body.decode('utf-8'))
        
        # Extract the necessary fields from the callback
        stk_callback = result_json.get('Body', {}).get('stkCallback', {})
        result_code = stk_callback.get('ResultCode')
        result_desc = stk_callback.get('ResultDesc')
        merchant_request_id = stk_callback.get('MerchantRequestID')
        checkout_request_id = stk_callback.get('CheckoutRequestID')
        
        # Initialize variables
        amount = None
        mpesa_receipt_number = None
        balance = None
        transaction_date = None
        phone_number = None
        
        # Extract CallbackMetadata Items
        callback_metadata = stk_callback.get('CallbackMetadata', {}).get('Item', [])
        for item in callback_metadata:
            if item['Name'] == 'Amount':
                amount = item['Value']
            elif item['Name'] == 'MpesaReceiptNumber':
                mpesa_receipt_number = item['Value']
            elif item['Name'] == 'Balance':
                balance = item.get('Value', None)
            elif item['Name'] == 'TransactionDate':
                transaction_date = datetime.strptime(str(item['Value']), "%Y%m%d%H%M%S")
            elif item['Name'] == 'PhoneNumber':
                phone_number = item['Value']
        
        # Save the data to the database
        payment = Payment.objects.create(
            merchant_request_id=merchant_request_id,
            checkout_request_id=checkout_request_id,
            result_code=result_code,
            result_description=result_desc,
            amount=amount,
            mpesa_receipt_number=mpesa_receipt_number,
            balance=balance,
            transaction_date=transaction_date,
            phone_number=phone_number
        )

        # Prepare the JSON response
        response_data = {
            "ResultCode": "0",
            "ResultDesc": "Success"
        }
        response_json = json.dumps(response_data)

        # Return the JSON response
        return HttpResponse(response_json, content_type='application/json')

    return HttpResponse('Method is not allowed', status=405)



@login_required
def routes(request):
    if request.method == "POST":
        form = RoutesForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('routes')
    else:
        form = RoutesForm()
    routes = Route.objects.all()
    return render(request, "busapp/admin/routes.html", {'routes':routes, 'form':form})

@login_required
def edit_route(request, route_id):
    route = get_object_or_404(Route, id=route_id)
    
    if request.method == "POST":
        form = RoutesForm(request.POST, instance=route)
        if form.is_valid():
            form.save()
            return redirect('routes')
    else:
        form = RoutesForm(instance=route)
    
    return render(request, 'busapp/admin/routes.html', {'form': form})

@login_required
def delete_route(request, pk):
    route = get_object_or_404(Route, pk=pk)
    route.delete()
    return redirect('routes')


@login_required
def list_buses(request):

busapp/templates/busapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bus Booking Web App</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    
    <!-- Select2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!-- DataTables CSS -->
    {% block extra_css %}{% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Bus Ticket Booking</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="#" class="nav-link"><b>Contact</b></a>
                    </li>
                    {% if user.is_authenticated %}
                    {% if user.is_staff %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'admin_account' %}"><b>Account</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user_account' %}"><b>Account</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'logout' %}"><b>Logout</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'register_user' %}"><b>Register</b></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'login' %}"><b>Login</b></a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Flash messages start -->
    <div class="container mt-3">
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    {{ message|safe|escape }}
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    {{ message|safe }}
                </div>
            {% elif message.tags == 'info' %}
                <div class="alert alert-info alert-dismissible" role="alert">
                    {{ message|safe|escape }}
                </div>
            {% elif message.tags == 'warning' %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                    {{ message|safe|escape }}
                </div>
            {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    <!-- end of flash messages -->

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="footer mt-4">
        <div class="container">
            <p>&copy; 2024 BusBooking. All Rights Reserved.</p>
            <p>Contact us: info@busbooking.com | +123-456-7890</p>
        </div>
    </footer>

    <!-- jQuery (Full version) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    {% block extra_js %}{% endblock %}
    <!-- Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- chart js -->
</body>
</html>

busapp/templates/busapp/bus_search_results.html
{% extends "busapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<section class="available-buses-section">
    <div class="container">
        <a class="btn btn-primary rounded-circle mb-3" href="{% url 'index' %}"><i class="fas fa-arrow-left"></i></a>
        <h2 class="text-center mb-4">Buses on Route({{ route }}) date {{ travel_date }}</h2>
        <div class="row">
            {% if buses %}
            {% for bus in buses %}
            <div class="col-md-4 mb-4">
                <div class="card shadow-sm border-light h-100">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-3">
                            <i class="fa fa-bus-alt fa-2x mr-3 text-primary"></i>
                            <h5 class="card-title mb-0">{{ bus.number_plate }}</h5>
                        </div>
                        <div class="d-flex">
                            <p class="card-text mr-5"><strong>Available Seats:</strong> {{ bus.available_seats }}</p>
                            <p class="card-text"><strong>Price:</strong> Ksh {{route.price}}.00</p>
                        </div>
                        
                        <p class="card-text"><strong>Status:</strong> 
                            <span class="badge 
                            {% if bus.status == 'AVAILABLE' %}
                                badge-success
                            {% elif bus.status == 'BOOKED' %}
                                badge-danger
                            {% else %}
                                badge-secondary
                            {% endif %}
                            ">{{ bus.status }}</span>
                        </p>
                    </div>
                    <div class="card-footer bg-transparent border-top-0">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="bus_id" value="{{ bus.id }}">
                            <button class="btn btn-primary btn-block {% if bus.available_seats == 0 %}disabled{% endif %}" type="submit">
                                {% if bus.available_seats == 0 %}
                                    Sold Out
                                {% else %}
                                    Book Now
                                {% endif %}
                            </button>
                        </form>
                        
                    </div>
                </div>
            </div>
        {% endfor %}

            {% else %}
            <div class="col-12">
                <p class="text-center text-muted">No buses available for the selected route and travel date.</p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

busapp/templates/busapp/contact.html
{% extends "busapp/base.html" %}
{% load static %}
{% block content%}
    <div class="container">
        <div class="card">
            <h2>CONTACT US</h2>
            <div class="card-body">
            </div>
        </div>
    </div>

{% endblock %}

busapp/templates/busapp/index.html
{% extends "busapp/base.html" %}
{% load static %}
{% block content%}
<style>
    .card {
    border-radius: 8px;
    transition: transform 0.2s ease-in-out;
}

.card:hover {
    transform: translateY(-5px);
}

.card-title {
    font-weight: 600;
}

.card-footer {
    padding: 0.75rem;
}

.btn-primary {
    background-color: #007bff;
    border-color: #007bff;
}

.badge-success {
    background-color: #28a745;
}

.badge-danger {
    background-color: #dc3545;
}

.badge-secondary {
    background-color: #6c757d;
}
</style>
    <!-- Hero Section -->
    <section class="hero-section">
        <div class="container">
            <h1 class="display-4">Travel with Comfort and Ease</h1>
            <p class="lead">Book your bus tickets in just a few clicks and enjoy your journey.</p>
            <a href="#bus-search" class="btn btn-primary btn-lg">Book Now</a>
        </div>
    </section>

    <!-- Bus Search Section -->
    <section class="bus-search-section py-5">
        <div class="container" id="bus-search">
            <h2 class="text-center mb-4">Find Your Bus</h2>
            
            <form method="POST" action="{% url 'index' %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-8 mb-3">
                        <label for="id_route">Routes</label>
                        <select class="form-control" id="id_route" name="route" style="width: 100%;">
                            {% for choice in form.route.field.queryset %}
                            <option value="{{ choice.id }}">{{ choice }}</option>
                            {% endfor %}
                        </select>
                        
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="date">Travel Date</label>
                        <input type="date" class="form-control" id="date" required name="travel_date">
                    </div>
                </div>
                <button class="btn btn-primary btn-lg btn-block" type="submit">Search Buses</button>
            </form>
        </div> 
    </section>
    
    
        
        

    <!-- Features Section -->
    <section class="features-section">
        <div class="container">
            <h2 class="text-center mb-5">Why Choose Us?</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="card feature-card">
                        <img src="{% static '/images/reliable_service.jpg' %}" class="card-img-top" alt="Reliable Service">
                        <div class="card-body">
                            <h5 class="card-title">Reliable Service</h5>
                            <p class="card-text">We offer reliable and timely bus services with a wide network across the country.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card feature-card">
                        <img src="{% static 'images/safe_travels.jpg' %}" class="card-img-top" alt="Safe Travel">
                        <div class="card-body">
                            <h5 class="card-title">Safe Travel</h5>
                            <p class="card-text">Your safety is our priority. Travel with confidence knowing you’re in good hands.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card feature-card">
                        <img src="{% static 'images/affordable_price.webp' %}" class="card-img-top" alt="Affordable Prices">
                        <div class="card-body">
                            <h5 class="card-title">Affordable Prices</h5>
                            <p class="card-text">Enjoy affordable and transparent pricing with no hidden fees.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
   {% endblock %}